E=set(map(int,input("Enter numbers").split(",")))
N=set(map(int,input("Enter numbers").split(",")))
print("Union of E and N is",E|N)
print("Intersection of E and N is",E&N)
print("Difference of E and N is",E-N)
print("Symmetric difference of E and N is",E^N)
